---
- hosts: ansible
  become: true

  tasks:
  - name: create docker image using war file
    command: docker build -t cgnet-devops-image:latest .
    args:
      chdir: /opt/dockerimages

  - name: create tag to image
    command: docker tag cgnet-devops-image mydockhubaccount/cgnet-devops-image

  - name: push image on to dockerhub
    command: docker push mydockhubaccount/cgnet-devops-image

  - name: remove docker images form ansible server
    command: docker rmi cgnet-devops-image:latest mydockhubaccount/cgnet-devops-image
    ignore_errors: yes
